# Generated by Django 5.2 on 2025-09-29 13:34

import django.core.validators
import edubooks.supabase_adapter
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200)),
                ('programa', models.CharField(default='General', help_text='Programa académico al que pertenece la bibliografía', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('es_publica', models.BooleanField(default=True, help_text='Si es visible para estudiantes del programa')),
            ],
            options={
                'db_table': 'bibliografias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('año_publicacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)])),
                ('categoria', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Reservado', 'Reservado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=15)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'libros',
                'ordering': ['titulo'],
            },
            bases=(models.Model, edubooks.supabase_adapter.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('devolucion', 'Devolución'), ('sancion', 'Sanción'), ('general', 'General')], default='general', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('relacionado_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('renovaciones', models.PositiveIntegerField(default=0)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('notificado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'prestamos',
                'ordering': ['-fecha_prestamo'],
            },
            bases=(models.Model, edubooks.supabase_adapter.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=12)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Multa', 'Multa'), ('Suspensión', 'Suspensión')], max_length=12)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_suspension', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pagada', 'Pagada'), ('Completada', 'Completada')], default='Activa', max_length=12)),
            ],
            options={
                'db_table': 'sanciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
