# Generated by Django 5.2 on 2025-09-29 13:34

import django.core.validators
import django.db.models.deletion
import edubooks.supabase_adapter
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200)),
                ('programa', models.CharField(default='General', help_text='Programa académico al que pertenece la bibliografía', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('es_publica', models.BooleanField(default=True, help_text='Si es visible para estudiantes del programa')),
            ],
            options={
                'db_table': 'bibliografias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('año_publicacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2030)])),
                ('categoria', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('Reservado', 'Reservado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=15)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'libros',
                'ordering': ['titulo'],
            },
            bases=(models.Model, edubooks.supabase_adapter.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('devolucion', 'Devolución'), ('sancion', 'Sanción'), ('general', 'General')], default='general', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('relacionado_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_libros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('renovaciones', models.PositiveIntegerField(default=0)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prestamos',
                'ordering': ['-fecha_prestamo'],
            },
            bases=(models.Model, edubooks.supabase_adapter.SupabaseModelMixin),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Activa', max_length=12)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Multa', 'Multa'), ('Suspensión', 'Suspensión')], max_length=12)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_suspension', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Pagada', 'Pagada'), ('Completada', 'Completada')], default='Activa', max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sanciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        # Agregar relaciones de ForeignKey que dependen de otros modelos
        migrations.AddField(
            model_name='bibliografia',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='bibliografias', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='libros.prestamo'),
        ),
        # Agregar índices para optimización
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='idx_libro_titulo'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='idx_libro_autor'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['isbn'], name='idx_libro_isbn'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria'], name='idx_libro_categoria'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['editorial'], name='idx_libro_editorial'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['estado'], name='idx_libro_estado'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['ubicacion'], name='idx_libro_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['año_publicacion'], name='idx_libro_año_publicacion'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['cantidad_disponible'], name='idx_libro_cantidad_disponible'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['cantidad_total'], name='idx_libro_cantidad_total'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['fecha_registro'], name='idx_libro_fecha_registro'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria', 'estado'], name='idx_libro_categoria_estado'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['estado', 'cantidad_disponible'], name='idx_libro_estado_disponible'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor', 'categoria'], name='idx_libro_autor_categoria'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo', 'autor'], name='idx_libro_titulo_autor'),
        ),
        # Agregar restricciones de unicidad
        migrations.AlterUniqueTogether(
            name='bibliografia',
            unique_together={('docente', 'curso', 'programa')},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('libro', 'usuario', 'estado')},
        ),
    ]
