# Generated by Django 5.2 on 2025-09-29 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliografia',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='idx_libro_titulo'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='idx_libro_autor'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['isbn'], name='idx_libro_isbn'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria'], name='idx_libro_categoria'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['editorial'], name='idx_libro_editorial'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['estado'], name='idx_libro_estado'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['ubicacion'], name='idx_libro_ubicacion'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['año_publicacion'], name='idx_libro_año_publicacion'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['cantidad_disponible'], name='idx_libro_cantidad_disponible'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['cantidad_total'], name='idx_libro_cantidad_total'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['fecha_registro'], name='idx_libro_fecha_registro'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria', 'estado'], name='idx_libro_categoria_estado'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['estado', 'cantidad_disponible'], name='idx_libro_estado_disponible'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor', 'categoria'], name='idx_libro_autor_categoria'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo', 'autor'], name='idx_libro_titulo_autor'),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='bibliografias', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_libros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sancion',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='libros.prestamo'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bibliografia',
            unique_together={('docente', 'curso', 'programa')},
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('libro', 'usuario', 'estado')},
        ),
    ]
