# Generated by Django 4.2.7 on 2025-09-10 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bibliografia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='es_publica',
            field=models.BooleanField(default=True, help_text='Si es visible para estudiantes del programa'),
        ),
        migrations.AddField(
            model_name='bibliografia',
            name='programa',
            field=models.CharField(default='General', help_text='Programa académico al que pertenece la bibliografía', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='bibliografia',
            unique_together={('docente', 'curso', 'programa')},
        ),
    ]
