# Generated by Django 4.2.7 on 2025-09-16 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0002_alter_bibliografia_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
