# Generated by Django 5.2 on 2025-09-28 07:18

import django.db.models.deletion
import edubooks.supabase_adapter
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Administrador', 'Administrador')], max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido'), ('Graduado', 'Graduado'), ('Retirado', 'Retirado')], default='Activo', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decir')], max_length=1, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('prestamos_activos', models.PositiveIntegerField(default=0)),
                ('max_prestamos_permitidos', models.PositiveIntegerField(default=3)),
                ('multas_pendientes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_ultima_sancion', models.DateTimeField(blank=True, null=True)),
                ('sancionado_hasta', models.DateTimeField(blank=True, null=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=True)),
                ('idioma_preferido', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('semestre_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_graduacion_esperada', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_empleado', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('grado_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_acceso', models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Super Administrador')], default=1)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            bases=(models.Model, edubooks.supabase_adapter.SupabaseModelMixin),
        ),
    ]
