# Generated by Django 5.2 on 2025-11-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='fecha_contratacion',
        ),
    ]
