# Generated by Django 5.2 on 2025-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_docente_fecha_contratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
